#+TITLE:   The Council of Protestants in Guiding and Scouting (CPGS)
#+AUTHOR:    Annette von Stockhausen
#+EMAIL:     Annette von Stockhausen <Annette.von.Stockhausen@vcp.de>
#+DESCRIPTION: Website of the Council of Protestants in Guiding and Scouting (CPGS), a link of confessional Protestant Guide and Scout associations and of Pastoral Protestant committees which enjoys Consultative Status with the World Scout Committee.
#+KEYWORDS: scouts, scouting, christian, protestant
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="stylesheet.css" />
#+INCLUDE: "header/header.org"

* About
The Council of Protestants in Guiding and Scouting (CPGS) is a link of confessional Protestant Guide and Scout associations and of Pastoral Protestant committees. CPGS' understanding of Protestantism is based on the definition of the [[http://www.oikoumene.org/][World Council of Churches (WCC)]].

CPGS regards Scouting and Guiding as an important contributor to the physical, intellectual, social, emotional and spiritual development of youth. Furthermore, CPGS believes that all of the above mentioned dimensions of Scouting should be equally emphasized.

CPGS is a member of the [[http://www.scout.org/en/about_scouting/partners/interreligious/wsirf][Interreligious Forum of WOSM]] and a member of the Interreligious Youth Forum of the WCC.

The mission of CPGS is:
- To strengthen the members awareness of their Christian-Protestant background and the spiritual dimension in Scouting in general.
- A place to share practical ideas on how to make activities for Guides and Scouts, with emphasis on the spiritual dimension in Scouting.
- To motivate cooperation among members of CPGS.
- Establish Scouting wherever Protestant churches exist.

CPGS enjoys Consultative Status with the [[http://www.scout.org/][World Scout Committee]].
